PREFIX ex:   <http://ex.org/> 
SELECT
   ?CandidateName
   ?PartyName
   ?StateName
   ?ElectoralVotes
   ?PollClosedAt
   ?NumberOfCandidates
   ?CountyName
   ?NumberOfVotes
WHERE {
   ?candidate a ex:Candidate ;
      ex:name ?CandidateName ;
      ex:party ?PartyName .
   ?state a ex:State ;
      ex:name ?StateName ;
      ex:electoralVotes ?ElectoralVotes ;
      ex:pollClosedAt ?PollClosedAt ;
      ex:numberOfCandidates ?NumberOfCandidates .
   ?votes a ex:Votes ;
      ex:candidate ?CandidateName ;
      ex:county ?CountyName ;
      ex:state ?StateName ;
      ex:numberOfVotes ?NumberOfVotes .
}
ORDER BY ?StateName ?CountyName ?PartyName
LIMIT 10